version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%\Packaging\xbox-one

build_script:
  - build.bat
artifacts:
  - path: .
    name: devilutionX_*_x64.appx
  - path: .
    name: Microsoft.VCLibs.x64.*.appx
