/**
 * @file sfxdat.cpp
 *
 * Implementation of data related to sounds.
 */
#include "all.h"
#include "sfxdat.h"
#ifndef NOSOUND
#include <SDL_mixer.h>
#include "utils/soundsample.h"

DEVILUTION_BEGIN_NAMESPACE

/** List of all sounds, except monsters and music */
const SFXData sfxdata[61] = {
	// clang-format off
//_sfx_id          bFlags
/*PS_WALK1*/     { sfx_MISC                  },
/*PS_WALK2*///   { sfx_MISC                  },
/*PS_WALK3*///   { sfx_MISC                  },
/*PS_WALK4*///   { sfx_MISC                  },
/*PS_BFIRE*/     { sfx_MISC                  },
/*PS_FMAG*///    { sfx_MISC                  },
/*PS_TMAG*///    { sfx_MISC                  },
/*PS_LGHIT*///   { sfx_MISC                  },
/*PS_LGHIT1*///  { sfx_MISC                  },
/*PS_SWING*/     { sfx_MISC                  },
/*PS_SWING2*/    { sfx_MISC                  },
/*PS_DEAD*/      { sfx_MISC                  }, // Aaauh...
/*IS_STING1*///  { sfx_MISC | sfx_HELLFIRE   },
/*IS_FBALLBOW*///{ sfx_MISC | sfx_HELLFIRE   },
/*IS_QUESTDN*/   { sfx_STREAM                },
/*IS_ARMRFKD*/// { sfx_MISC                  },
/*IS_BARLFIRE*/  { sfx_MISC                  },
/*IS_BARREL*/    { sfx_MISC                  },
/*IS_POPPOP8*/   { sfx_MISC | sfx_HELLFIRE   },
/*IS_POPPOP5*/   { sfx_MISC | sfx_HELLFIRE   },
/*IS_POPPOP3*/   { sfx_MISC | sfx_HELLFIRE   },
/*IS_POPPOP2*/   { sfx_MISC | sfx_HELLFIRE   },
/*IS_CRCLOS*/    { sfx_MISC | sfx_HELLFIRE   },
/*IS_CROPEN*/    { sfx_MISC | sfx_HELLFIRE   },
/*IS_BHIT*///    { sfx_MISC                  },
/*IS_BHIT1*///   { sfx_MISC                  },
/*IS_CHEST*/     { sfx_MISC                  },
/*IS_DOORCLOS*/  { sfx_MISC                  },
/*IS_DOOROPEN*/  { sfx_MISC                  },
/*IS_FANVL*/     { sfx_MISC                  },
/*IS_FAXE*/      { sfx_MISC                  },
/*IS_FBLST*/     { sfx_MISC                  },
/*IS_FBODY*/     { sfx_MISC                  },
/*IS_FBOOK*/     { sfx_MISC                  },
/*IS_FBOW*/      { sfx_MISC                  },
/*IS_FCAP*/      { sfx_MISC                  },
/*IS_FHARM*/     { sfx_MISC                  },
/*IS_FLARM*/     { sfx_MISC                  },
/*IS_FMAG*///    { sfx_MISC                  },
/*IS_FMAG1*///   { sfx_MISC                  },
/*IS_FMUSH*/     { sfx_MISC                  },
/*IS_FPOT*/      { sfx_MISC                  },
/*IS_FRING*/     { sfx_MISC                  },
/*IS_FROCK*/     { sfx_MISC                  },
/*IS_FSCRL*/     { sfx_MISC                  },
/*IS_FSHLD*/     { sfx_MISC                  },
/*IS_FSIGN*///   { sfx_MISC                  },
/*IS_FSTAF*/     { sfx_MISC                  },
/*IS_FSWOR*/     { sfx_MISC                  },
/*IS_GOLD*/      { sfx_MISC                  },
/*IS_HLMTFKD*/// { sfx_MISC                  },
/*IS_IANVL*/     { sfx_MISC                  },
/*IS_IAXE*/      { sfx_MISC                  },
/*IS_IBLST*/     { sfx_MISC                  },
/*IS_IBODY*/     { sfx_MISC                  },
/*IS_IBOOK*/     { sfx_MISC                  },
/*IS_IBOW*/      { sfx_MISC                  },
/*IS_ICAP*/      { sfx_MISC                  },
/*IS_IGRAB*/     { sfx_MISC                  },
/*IS_IHARM*/     { sfx_MISC                  },
/*IS_ILARM*/     { sfx_MISC                  },
/*IS_IMUSH*/     { sfx_MISC                  },
/*IS_IPOT*/      { sfx_MISC                  },
/*IS_IRING*/     { sfx_MISC                  },
/*IS_IROCK*/     { sfx_MISC                  },
/*IS_ISCROL*/    { sfx_MISC                  },
/*IS_ISHIEL*/    { sfx_MISC                  },
/*IS_ISIGN*/     { sfx_MISC                  },
/*IS_ISTAF*/     { sfx_MISC                  },
/*IS_ISWORD*/    { sfx_MISC                  },
/*IS_LEVER*/     { sfx_MISC                  },
/*IS_MAGIC*/     { sfx_MISC                  },
/*IS_MAGIC1*/    { sfx_MISC                  },
/*IS_RBOOK*/     { sfx_MISC                  },
/*IS_SARC*/      { sfx_MISC                  },
/*IS_SHLDFKD*/// { sfx_MISC                  },
/*IS_SWRDFKD*/// { sfx_MISC                  },
/*IS_TITLEMOV*/  { sfx_UI                    },
/*IS_TITLSLCT*/  { sfx_UI                    },
	// clang-format on
};

const SFXFileData sfxfiledata[61] = {
	// clang-format off
//_sfx_id          pszName
/*PS_WALK1*/     { "Sfx\\Misc\\Walk1.wav"     },
/*PS_WALK2*///   { "Sfx\\Misc\\Walk2.wav"     },
/*PS_WALK3*///   { "Sfx\\Misc\\Walk3.wav"     },
/*PS_WALK4*///   { "Sfx\\Misc\\Walk4.wav"     },
/*PS_BFIRE*/     { "Sfx\\Misc\\BFire.wav"     },
/*PS_FMAG*///    { "Sfx\\Misc\\Fmag.wav"      },
/*PS_TMAG*///    { "Sfx\\Misc\\Tmag.wav"      },
/*PS_LGHIT*///   { "Sfx\\Misc\\Lghit.wav"     },
/*PS_LGHIT1*///  { "Sfx\\Misc\\Lghit1.wav"    },
/*PS_SWING*/     { "Sfx\\Misc\\Swing.wav"     },
/*PS_SWING2*/    { "Sfx\\Misc\\Swing2.wav"    },
/*PS_DEAD*/      { "Sfx\\Misc\\Dead.wav"      }, // Aaauh...
/*IS_STING1*///  { "Sfx\\Misc\\Sting1.wav"    },
/*IS_FBALLBOW*///{ "Sfx\\Misc\\FBallBow.wav"  },
/*IS_QUESTDN*/   { "Sfx\\Misc\\Questdon.wav"  },
/*IS_ARMRFKD*/// { "Sfx\\Items\\Armrfkd.wav"  },
/*IS_BARLFIRE*/  { "Sfx\\Items\\Barlfire.wav" },
/*IS_BARREL*/    { "Sfx\\Items\\Barrel.wav"   },
/*IS_POPPOP8*/   { "Sfx\\Items\\PodPop8.wav"  },
/*IS_POPPOP5*/   { "Sfx\\Items\\PodPop5.wav"  },
/*IS_POPPOP3*/   { "Sfx\\Items\\UrnPop3.wav"  },
/*IS_POPPOP2*/   { "Sfx\\Items\\UrnPop2.wav"  },
/*IS_CRCLOS*/    { "Sfx\\Items\\Crclos.wav"   },
/*IS_CROPEN*/    { "Sfx\\Items\\Cropen.wav"   },
/*IS_BHIT*///    { "Sfx\\Items\\Bhit.wav"     },
/*IS_BHIT1*///   { "Sfx\\Items\\Bhit1.wav"    },
/*IS_CHEST*/     { "Sfx\\Items\\Chest.wav"    },
/*IS_DOORCLOS*/  { "Sfx\\Items\\Doorclos.wav" },
/*IS_DOOROPEN*/  { "Sfx\\Items\\Dooropen.wav" },
/*IS_FANVL*/     { "Sfx\\Items\\Flipanvl.wav" },
/*IS_FAXE*/      { "Sfx\\Items\\Flipaxe.wav"  },
/*IS_FBLST*/     { "Sfx\\Items\\Flipblst.wav" },
/*IS_FBODY*/     { "Sfx\\Items\\Flipbody.wav" },
/*IS_FBOOK*/     { "Sfx\\Items\\Flipbook.wav" },
/*IS_FBOW*/      { "Sfx\\Items\\Flipbow.wav"  },
/*IS_FCAP*/      { "Sfx\\Items\\Flipcap.wav"  },
/*IS_FHARM*/     { "Sfx\\Items\\Flipharm.wav" },
/*IS_FLARM*/     { "Sfx\\Items\\Fliplarm.wav" },
/*IS_FMAG*///    { "Sfx\\Items\\Flipmag.wav"  },
/*IS_FMAG1*///   { "Sfx\\Items\\Flipmag1.wav" },
/*IS_FMUSH*/     { "Sfx\\Items\\Flipmush.wav" },
/*IS_FPOT*/      { "Sfx\\Items\\Flippot.wav"  },
/*IS_FRING*/     { "Sfx\\Items\\Flipring.wav" },
/*IS_FROCK*/     { "Sfx\\Items\\Fliprock.wav" },
/*IS_FSCRL*/     { "Sfx\\Items\\Flipscrl.wav" },
/*IS_FSHLD*/     { "Sfx\\Items\\Flipshld.wav" },
/*IS_FSIGN*///   { "Sfx\\Items\\Flipsign.wav" },
/*IS_FSTAF*/     { "Sfx\\Items\\Flipstaf.wav" },
/*IS_FSWOR*/     { "Sfx\\Items\\Flipswor.wav" },
/*IS_GOLD*/      { "Sfx\\Items\\Gold.wav"     },
/*IS_HLMTFKD*/// { "Sfx\\Items\\Hlmtfkd.wav"  },
/*IS_IANVL*/     { "Sfx\\Items\\Invanvl.wav"  },
/*IS_IAXE*/      { "Sfx\\Items\\Invaxe.wav"   },
/*IS_IBLST*/     { "Sfx\\Items\\Invblst.wav"  },
/*IS_IBODY*/     { "Sfx\\Items\\Invbody.wav"  },
/*IS_IBOOK*/     { "Sfx\\Items\\Invbook.wav"  },
/*IS_IBOW*/      { "Sfx\\Items\\Invbow.wav"   },
/*IS_ICAP*/      { "Sfx\\Items\\Invcap.wav"   },
/*IS_IGRAB*/     { "Sfx\\Items\\Invgrab.wav"  },
/*IS_IHARM*/     { "Sfx\\Items\\Invharm.wav"  },
/*IS_ILARM*/     { "Sfx\\Items\\Invlarm.wav"  },
/*IS_IMUSH*/     { "Sfx\\Items\\Invmush.wav"  },
/*IS_IPOT*/      { "Sfx\\Items\\Invpot.wav"   },
/*IS_IRING*/     { "Sfx\\Items\\Invring.wav"  },
/*IS_IROCK*/     { "Sfx\\Items\\Invrock.wav"  },
/*IS_ISCROL*/    { "Sfx\\Items\\Invscrol.wav" },
/*IS_ISHIEL*/    { "Sfx\\Items\\Invshiel.wav" },
/*IS_ISIGN*/     { "Sfx\\Items\\Invsign.wav"  },
/*IS_ISTAF*/     { "Sfx\\Items\\Invstaf.wav"  },
/*IS_ISWORD*/    { "Sfx\\Items\\Invsword.wav" },
/*IS_LEVER*/     { "Sfx\\Items\\Lever.wav"    },
/*IS_MAGIC*/     { "Sfx\\Items\\Magic.wav"    },
/*IS_MAGIC1*/    { "Sfx\\Items\\Magic1.wav"   },
/*IS_RBOOK*/     { "Sfx\\Items\\Readbook.wav" },
/*IS_SARC*/      { "Sfx\\Items\\Sarc.wav"     },
/*IS_SHLDFKD*/// { "Sfx\\Items\\Shielfkd.wav" },
/*IS_SWRDFKD*/// { "Sfx\\Items\\Swrdfkd.wav"  },
/*IS_TITLEMOV*/  { "Sfx\\Items\\Titlemov.wav" },
/*IS_TITLSLCT*/  { "Sfx\\Items\\Titlslct.wav" },
	// clang-format on
};

DEVILUTION_END_NAMESPACE

#endif // NOSOUND
