set(ASAN OFF)
set(UBSAN OFF)

set(NONET ON)
#set(DEVILUTIONX_SYSTEM_BZIP2 OFF)

#set(BUILD_ASSETS_MPQ OFF)
#set(DEVILUTIONX_ASSETS_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/pkg/assets")

#set(DEVILUTIONX_RESAMPLER_SPEEX OFF)
#set(DEFAULT_AUDIO_BUFFER_SIZE 5120)

set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
