/**
 * @file objdat.cpp
 *
 * Implementation of all object data.
 */
#include "all.h"

DEVILUTION_BEGIN_NAMESPACE

/** Maps from dun_object_id to object_id. */
const BYTE ObjConvTbl[128] = {
	// clang-format off
	0,
	OBJ_LEVER, // Q_SKELKING
	OBJ_CRUXM, // Q_SKELKING
	OBJ_CRUXR, // Q_SKELKING
	OBJ_CRUXL, // Q_SKELKING
	0, //OBJ_ANGEL,
	0, //OBJ_BANNERL,
	0, //OBJ_BANNERM,
	0, //OBJ_BANNERR,
	0,
	0,
	0,
	0,
	0,
	OBJ_BOOK2L, // Q_SCHAMB, Q_BETRAYER
	0, //OBJ_BOOK2R,
	OBJ_TBCROSS, // Q_SCHAMB
	0,
	0, //OBJ_CANDLE1,
	OBJ_CANDLE2, // Q_SCHAMB
	0, //OBJ_CANDLEO,
	0, //OBJ_CAULDRON,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0, //OBJ_FLAMEHOLE,
	0,
	0,
	0,
	0,
	0,
	OBJ_MCIRCLE1, // Q_BETRAYER
	OBJ_MCIRCLE2, // Q_BETRAYER
	0, //OBJ_SKFIRE,
	0, //OBJ_SKPILE,
	0, //OBJ_SKSTICK1,
	0, //OBJ_SKSTICK2,
	0, //OBJ_SKSTICK3,
	0, //OBJ_SKSTICK4,
	0, //OBJ_SKSTICK5,
	0,
	0,
	0,
	0,
	0,
	0,
	OBJ_SWITCHSKL, // Q_SCHAMB
	0,
	0, //OBJ_TRAPL,
	0, //OBJ_TRAPR,
	OBJ_TORTURE1, // Q_BUTCHER
	OBJ_TORTURE2, // Q_BUTCHER
	OBJ_TORTURE3, // Q_BUTCHER
	OBJ_TORTURE4, // Q_BUTCHER
	OBJ_TORTURE5, // Q_BUTCHER
	0,
	0,
	0,
	0,
	0,
	0, //OBJ_NUDEW2R,
	0,
	0,
	0,
	0,
	OBJ_TNUDEM, //1, Q_BUTCHER
	OBJ_TNUDEM, //2, Q_BUTCHER
	OBJ_TNUDEM, //3, Q_BUTCHER
	OBJ_TNUDEM, //4, Q_BUTCHER
	OBJ_TNUDEW, //1, Q_BUTCHER
	OBJ_TNUDEW, //2, Q_BUTCHER
	OBJ_TNUDEW, //3, Q_BUTCHER
	0, //OBJ_CHEST1,
	OBJ_CHEST1, // Q_SKELKING
	0, //OBJ_CHEST1,
	0, //OBJ_CHEST2,
	OBJ_CHEST2, // Q_SKELKING
	0, //OBJ_CHEST2,
	0, //OBJ_CHEST3,
	OBJ_CHEST3, // Q_SCHAMB
	0, //OBJ_CHEST3,
	0,
	0,
	0,
	0,
	0,
	0, //OBJ_PEDISTAL,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	OBJ_ALTBOY, // Q_BETRAYER
	0,
	0,
	OBJ_WEAPONRACKL, //OBJ_ARMORSTAND, // Q_WARLORD - swapped from original to reduce farming potential
	OBJ_ARMORSTAND, //OBJ_WEAPONRACKL, // Q_WARLORD
	OBJ_TORCHR2, // Q_BLOOD
	OBJ_TORCHL2, // Q_BLOOD
	0, //OBJ_MUSHPATCH,
	0, //OBJ_STAND,
	0, //OBJ_TORCHL,
	0, //OBJ_TORCHR,
	0, //OBJ_FLAMELVR,
	0, //OBJ_SARC,
	0, //OBJ_BARREL,
	0, //OBJ_BARRELEX,
	0, //OBJ_BOOKSHELF,
	0, //OBJ_BOOKCASEL,
	0, //OBJ_BOOKCASER,
	0, //OBJ_ARMORSTANDN,
	0, //OBJ_WEAPONRACKLN,
	0, //OBJ_BLOODFTN,
	0, //OBJ_PURIFYINGFTN,
	0, //OBJ_SHRINEL,
//	0, //OBJ_SHRINER,
//	0, //OBJ_GOATSHRINE,
//	0, //OBJ_MURKYFTN,
//	0, //OBJ_TEARFTN,
//	0, //OBJ_DECAP,
//	0, //OBJ_TCHEST1,
//	0, //OBJ_TCHEST2,
//	0, //OBJ_TCHEST3,
//	0, //OBJ_LAZSTAND,
//	0, //OBJ_BOOKSTAND,
//	0, //OBJ_BOOKSHELFR,
	// clang-format on
};

/** Contains the data related to each object ID. */
const ObjectData objectdata[NUM_OBJECTS] = {
	// clang-format off
//_object_id          ofindex,        oLvlTypes,                                 oSetLvlType,     otheme,                  oquest,    oAnimBaseFrame, oDoorFlag, oSelFlag, oTrapFlag,
/*OBJ_L1LIGHT*/		{ OFILE_L1BRAZ,   DTM_CATHEDRAL,                             DTYPE_CATHEDRAL, THEME_NONE,              Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_L1LDOOR*/		{ OFILE_L1DOORS,  DTM_CATHEDRAL,                             DTYPE_CATHEDRAL, THEME_NONE,              Q_INVALID,              1,  ODT_LEFT,        3, TRUE      },
/*OBJ_L1RDOOR*/		{ OFILE_L1DOORS,  DTM_CATHEDRAL,                             DTYPE_CATHEDRAL, THEME_NONE,              Q_INVALID,              2, ODT_RIGHT,        3, TRUE      },
/*OBJ_SKFIRE*/		{ OFILE_SKULFIRE, 0,                                         0,               THEME_SKELROOM,          Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_LEVER*/		{ OFILE_LEVER,    0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, FALSE     },
/*OBJ_CHEST1*/		{ OFILE_CHEST1,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, TRUE      },
/*OBJ_CHEST2*/		{ OFILE_CHEST2,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, TRUE      },
/*OBJ_CHEST3*/		{ OFILE_CHEST3,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, TRUE      },
/*OBJ_CANDLE1*/	//	{ OFILE_CANDLE,   0,                                         0,               THEME_NONE,              Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_CANDLE2*/		{ OFILE_CANDLE2,  0,                                         0,               THEME_SHRINE,            Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_CANDLEO*/	//	{ OFILE_CANDLABR, 0,                                         0,               THEME_NONE,              Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_BANNERL*/		{ OFILE_BANNER,   0,                                         0,               THEME_SKELROOM,          Q_INVALID,              2,  ODT_NONE,        0, FALSE     },
/*OBJ_BANNERM*/		{ OFILE_BANNER,   0,                                         0,               THEME_SKELROOM,          Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_BANNERR*/		{ OFILE_BANNER,   0,                                         0,               THEME_SKELROOM,          Q_INVALID,              3,  ODT_NONE,        0, FALSE     },
/*OBJ_SKPILE*/	//	{ OFILE_SKULPILE, 0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_SKSTICK1*///	{ OFILE_SKULSTIK, 0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_SKSTICK2*///	{ OFILE_SKULSTIK, 0,                                         0,               THEME_NONE,              Q_INVALID,              2,  ODT_NONE,        0, FALSE     },
/*OBJ_SKSTICK3*///	{ OFILE_SKULSTIK, 0,                                         0,               THEME_NONE,              Q_INVALID,              3,  ODT_NONE,        0, FALSE     },
/*OBJ_SKSTICK4*///	{ OFILE_SKULSTIK, 0,                                         0,               THEME_NONE,              Q_INVALID,              4,  ODT_NONE,        0, FALSE     },
/*OBJ_SKSTICK5*///	{ OFILE_SKULSTIK, 0,                                         0,               THEME_NONE,              Q_INVALID,              5,  ODT_NONE,        0, FALSE     },
/*OBJ_CRUXM*/		{ OFILE_CRUXSK1,  0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_CRUXR*/		{ OFILE_CRUXSK2,  0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_CRUXL*/		{ OFILE_CRUXSK3,  0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_STAND*/		{ OFILE_ROCKSTAN, 0,                                         0,               THEME_NONE,              Q_ROCK,                 1,  ODT_NONE,        0, FALSE     },
/*OBJ_ANGEL*/	//	{ OFILE_ANGEL,    0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_NUDEW2R*/	//	{ OFILE_NUDE2,    0,                                         0,               THEME_NONE,              Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_SWITCHSKL*/	{ OFILE_SWITCH4,  DTM_HELL,                                  0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, TRUE      },
/*OBJ_TNUDEM*/		{ OFILE_TNUDEM,   DTM_HELL,                                  0,               THEME_TORTURE,           Q_BUTCHER,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_TNUDEW*/		{ OFILE_TNUDEW,   DTM_HELL,                                  0,               THEME_TORTURE,           Q_BUTCHER,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_TORTURE1*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_TORTURE2*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,              2,  ODT_NONE,        0, FALSE     },
/*OBJ_TORTURE3*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,              3,  ODT_NONE,        0, FALSE     },
/*OBJ_TORTURE4*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,              4,  ODT_NONE,        0, FALSE     },
/*OBJ_TORTURE5*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,              5,  ODT_NONE,        0, FALSE     },
/*OBJ_L2LDOOR*/		{ OFILE_L2DOORS,  DTM_CATACOMBS,                             DTYPE_CATACOMBS, THEME_NONE,              Q_INVALID,              1,  ODT_LEFT,        3, TRUE      },
/*OBJ_L2RDOOR*/		{ OFILE_L2DOORS,  DTM_CATACOMBS,                             DTYPE_CATACOMBS, THEME_NONE,              Q_INVALID,              2, ODT_RIGHT,        3, TRUE      },
/*OBJ_TORCHL*/		{ OFILE_WTORCH4,  DTM_CATACOMBS,                             0,               THEME_NONE,              Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_TORCHR*/		{ OFILE_WTORCH3,  DTM_CATACOMBS,                             0,               THEME_NONE,              Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_TORCHL2*/		{ OFILE_WTORCH1,  DTM_CATACOMBS,                             0,               THEME_NONE,              Q_BLOOD,                0,  ODT_NONE,        0, FALSE     },
/*OBJ_TORCHR2*/		{ OFILE_WTORCH2,  DTM_CATACOMBS,                             0,               THEME_NONE,              Q_BLOOD,                0,  ODT_NONE,        0, FALSE     },
/*OBJ_SARC*/		{ OFILE_SARC,     DTM_CATHEDRAL,                             0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, TRUE      },
/*OBJ_FLAMEHOLE*///	{ OFILE_FLAME1,   0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_FLAMELVR*///	{ OFILE_LEVER,    0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, FALSE     },
/*OBJ_WATER*/	//	{ OFILE_MINIWATR, 0,                                         0,               THEME_NONE,              Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_TRAPL*/		{ OFILE_TRAPHOLE, DTM_CATHEDRAL | DTM_CATACOMBS | DTM_CRYPT, 0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_TRAPR*/		{ OFILE_TRAPHOLE, DTM_CATHEDRAL | DTM_CATACOMBS | DTM_CRYPT, 0,               THEME_NONE,              Q_INVALID,              2,  ODT_NONE,        0, FALSE     },
/*OBJ_BOOKSHELF*///	{ OFILE_BCASE,    0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_WEAPRACK*///	{ OFILE_WEAPSTND, 0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_BARREL*/		{ OFILE_BARREL,   DTM_ANY & ~(DTM_CRYPT | DTM_NEST),         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_BARRELEX*/	{ OFILE_BARRELEX, DTM_ANY & ~(DTM_CRYPT | DTM_NEST),         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_SHRINEL*/		{ OFILE_LSHRINEG, 0,                                         0,               THEME_SHRINE,            Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_SHRINER*/		{ OFILE_RSHRINEG, 0,                                         0,               THEME_SHRINE,            Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_BOOKCASEL*/	{ OFILE_BCASE,    0,                                         0,               THEME_LIBRARY,           Q_INVALID,              3,  ODT_NONE,        3, FALSE     },
/*OBJ_BOOKCASER*/	{ OFILE_BCASE,    0,                                         0,               THEME_LIBRARY,           Q_INVALID,              4,  ODT_NONE,        3, FALSE     },
/*OBJ_BOOKCANDLE*/	{ OFILE_CANDLE2,  0,                                         0,               THEME_LIBRARY,           Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_BLOODFTN*/	{ OFILE_BLOODFNT, 0,                                         0,               THEME_BLOODFOUNTAIN,     Q_INVALID,              0,  ODT_NONE,        3, FALSE     },
/*OBJ_DECAP*/		{ OFILE_DECAP,    DTM_HELL,                                  0,               THEME_DECAPITATED,       Q_INVALID,              0,  ODT_NONE,        1, FALSE     },
/*OBJ_TCHEST1*/		{ OFILE_CHEST1,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, FALSE     },
/*OBJ_TCHEST2*/		{ OFILE_CHEST2,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, FALSE     },
/*OBJ_TCHEST3*/		{ OFILE_CHEST3,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, FALSE     },
/*OBJ_BOOK2L*/		{ OFILE_BOOK2,    0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_BOOK2R*/		{ OFILE_BOOK2,    0,                                         0,               THEME_NONE,              Q_SCHAMB,               4,  ODT_NONE,        3, FALSE     },
/*OBJ_BOOKSTAND*/	{ OFILE_BOOK2,    0,                                         0,               THEME_LIBRARY,           Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_SKELBOOK*/	{ OFILE_BOOK2,    0,                                         0,               THEME_SKELROOM,          Q_INVALID,              4,  ODT_NONE,        3, FALSE     },
/*OBJ_BOOKLVR*/	//	{ OFILE_BOOK1,    0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_BLINDBOOK*/	{ OFILE_BOOK1,    0,                                         0,               THEME_NONE,              Q_BLIND,                1,  ODT_NONE,        3, FALSE     },
/*OBJ_BLOODBOOK*/	{ OFILE_BOOK1,    0,                                         0,               THEME_NONE,              Q_BLOOD,                4,  ODT_NONE,        3, FALSE     },
/*OBJ_STEELTOME*/	{ OFILE_BOOK1,    0,                                         0,               THEME_NONE,              Q_WARLORD,              4,  ODT_NONE,        3, FALSE     },
/*OBJ_PEDISTAL*/	{ OFILE_PEDISTL,  0,                                         0,               THEME_NONE,              Q_BLOOD,                1,  ODT_NONE,        3, FALSE     },
/*OBJ_L3LDOOR*/		{ OFILE_L3DOORS,  DTM_CAVES,                                 DTYPE_CAVES,     THEME_NONE,              Q_INVALID,              2,  ODT_LEFT,        3, TRUE      },
/*OBJ_L3RDOOR*/		{ OFILE_L3DOORS,  DTM_CAVES,                                 DTYPE_CAVES,     THEME_NONE,              Q_INVALID,              1, ODT_RIGHT,        3, TRUE      },
/*OBJ_PURIFYINGFTN*/{ OFILE_PFOUNTN,  0,                                         0,               THEME_PURIFYINGFOUNTAIN, Q_INVALID,              0,  ODT_NONE,        3, FALSE     },
/*OBJ_ARMORSTAND*/	{ OFILE_ARMSTAND, 0,                                         0,               THEME_ARMORSTAND,        Q_WARLORD,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_ARMORSTANDN*/	{ OFILE_ARMSTAND, 0,                                         0,               THEME_ARMORSTAND,        Q_INVALID,              2,  ODT_NONE,        0, FALSE     },
/*OBJ_GOATSHRINE*/	{ OFILE_GOATSHRN, 0,                                         0,               THEME_GOATSHRINE,        Q_INVALID,              0,  ODT_NONE,        3, FALSE     },
/*OBJ_CAULDRON*/	{ OFILE_CAULDREN, DTM_HELL,                                  0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_MURKYFTN*/	{ OFILE_MFOUNTN,  0,                                         0,               THEME_MURKYFOUNTAIN,     Q_INVALID,              0,  ODT_NONE,        3, FALSE     },
/*OBJ_TEARFTN*/		{ OFILE_TFOUNTN,  0,                                         0,               THEME_TEARFOUNTAIN,      Q_INVALID,              0,  ODT_NONE,        3, FALSE     },
/*OBJ_ALTBOY*/		{ OFILE_ALTBOY,   0,                                         0,               THEME_NONE,              Q_BETRAYER,             1,  ODT_NONE,        0, FALSE     },
/*OBJ_MCIRCLE1*/	{ OFILE_MCIRL,    0,                                         0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        0, FALSE     },
/*OBJ_MCIRCLE2*/	{ OFILE_MCIRL,    0,                                         0,               THEME_NONE,              Q_INVALID,              3,  ODT_NONE,        0, FALSE     },
/*OBJ_STORYBOOK*/	{ OFILE_BKSLBRNT, DTM_CATHEDRAL | DTM_CATACOMBS | DTM_CAVES, 0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     }, // BUGFIX should only be loaded on level 1-12 (crypt masks as 1-4) (fixed)
/*OBJ_STORYCANDLE*/	{ OFILE_CANDLE2,  DTM_CATHEDRAL | DTM_CATACOMBS | DTM_CAVES, 0,               THEME_NONE,              Q_BETRAYER,             0,  ODT_NONE,        0, FALSE     },
/*OBJ_TBCROSS*/		{ OFILE_BURNCROS, 0,                                         0,               THEME_BRNCROSS,          Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_WEAPONRACKL*/	{ OFILE_WEAPSTND, 0,                                         0,               THEME_WEAPONRACK,        Q_WARLORD,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_WEAPONRACKLN*/{ OFILE_WEAPSTND, 0,                                         0,               THEME_WEAPONRACK,        Q_INVALID,              2,  ODT_NONE,        0, FALSE     },
/*OBJ_WEAPONRACKR*/	{ OFILE_WEAPSTND, 0,                                         0,               THEME_WEAPONRACK,        Q_INVALID,              3,  ODT_NONE,        3, FALSE     },
/*OBJ_WEAPONRACKRN*/{ OFILE_WEAPSTND, 0,                                         0,               THEME_WEAPONRACK,        Q_INVALID,              4,  ODT_NONE,        0, FALSE     },
/*OBJ_MUSHPATCH*/	{ OFILE_MUSHPTCH, 0,                                         0,               THEME_NONE,              Q_MUSHROOM,             1,  ODT_NONE,        3, FALSE     },
/*OBJ_LAZSTAND*/	{ OFILE_LZSTAND,  0,                                         0,               THEME_NONE,              Q_BETRAYER,             1,  ODT_NONE,        3, FALSE     },
/*OBJ_SLAINHERO*/	{ OFILE_DECAP,    DTM_CAVES,                                 0,               THEME_NONE,              Q_INVALID,              2,  ODT_NONE,        1, FALSE     },
/*OBJ_SIGNCHEST*/	{ OFILE_CHEST3,   0,                                         0,               THEME_NONE,              Q_LTBANNER,             1,  ODT_NONE,        1, FALSE     },
/*OBJ_BOOKSHELFR*///{ OFILE_BCASE,    0,                                         0,               THEME_NONE,              Q_INVALID,              2,  ODT_NONE,        0, FALSE     },
#ifdef HELLFIRE
/*OBJ_L5LDOOR*/		{ OFILE_L5DOOR,   DTM_CRYPT,                                 0,               THEME_NONE,              Q_INVALID,              1,  ODT_LEFT,        3, TRUE      },
/*OBJ_L5RDOOR*/		{ OFILE_L5DOOR,   DTM_CRYPT,                                 0,               THEME_NONE,              Q_INVALID,              2, ODT_RIGHT,        3, TRUE      },
/*OBJ_L5SARC*/		{ OFILE_L5SARCO,  DTM_CRYPT,                                 0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, TRUE      },
/*OBJ_URN*/			{ OFILE_URN,      DTM_CRYPT,                                 0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_URNEX*/		{ OFILE_URNEXPLD, DTM_CRYPT,                                 0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_L5BOOK*/		{ OFILE_L5BOOKS,  DTM_CRYPT,                                 0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_L5CANDLE*/	{ OFILE_L5CANDLE, DTM_CRYPT,                                 0,               THEME_NONE,              Q_INVALID,              0,  ODT_NONE,        0, FALSE     },
/*OBJ_L5LEVER*/		{ OFILE_L5LEVER,  DTM_CRYPT,                                 0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        1, FALSE     },
/*OBJ_POD*/			{ OFILE_L6POD1,   DTM_NEST,                                  0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
/*OBJ_PODEX*/		{ OFILE_L6POD2,   DTM_NEST,                                  0,               THEME_NONE,              Q_INVALID,              1,  ODT_NONE,        3, FALSE     },
#endif
	// clang-format on
};

const ObjFileData objfiledata[NUM_OFILE_TYPES] = {
	// clang-format off
//object_graphic_id ofName,       oSFX,  oSFXCnt,   oAnimFlag, oAnimFrameLen, oAnimLen, oAnimWidth, oSolidFlag, oMissFlag, oLightFlag,     oBreak,
/*OFILE_L1BRAZ*/  {	"L1Braz",     SFX_NONE,    0,        TRUE,             1,       26,         64, TRUE,       TRUE,      FALSE, OBM_UNBREAKABLE },
/*OFILE_L1DOORS*/ {	"L1Doors",    IS_DOORCLOS, 2,       FALSE,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_LEVER*/   {	"Lever",      SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_CHEST1*/  {	"Chest1",     SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_CHEST2*/  {	"Chest2",     SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_BANNER*/  {	"Banner",     SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_SKULPILE*///{	"SkulPile",   SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_SKULFIRE*/{	"SkulFire",   SFX_NONE,    0,        TRUE,                 2,       11,         96, TRUE,       TRUE,      FALSE, OBM_UNBREAKABLE },
/*OFILE_SKULSTIK*///{	"SkulStik",   SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_CRUXSK1*/ {	"CruxSk1",    SFX_NONE,    0,       FALSE,             1,       15,         96, TRUE,       FALSE,     TRUE,    OBM_BREAKABLE },
/*OFILE_CRUXSK2*/ {	"CruxSk2",    SFX_NONE,    0,       FALSE,             1,       15,         96, TRUE,       FALSE,     TRUE,    OBM_BREAKABLE },
/*OFILE_CRUXSK3*/ {	"CruxSk3",    SFX_NONE,    0,       FALSE,             1,       15,         96, TRUE,       FALSE,     TRUE,    OBM_BREAKABLE },
/*OFILE_BOOK1*/   {	"Book1",      SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_BOOK2*/   {	"Book2",      SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_ROCKSTAN*/{	"Rockstan",   SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_ANGEL*/// {	"Angel",      SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_GHOST*/// {	"Ghost",      SFX_NONE,    0,        TRUE,             0,       14,        128, FALSE,       TRUE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_CHEST3*/  {	"Chest3",     SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_BURNCROS*/{	"Burncros",   SFX_NONE,    0,        TRUE,             1,       10,        160, TRUE,       FALSE,     FALSE, OBM_UNBREAKABLE },
/*OFILE_CANDLE*///{	"Candle",     SFX_NONE,    0,       FALSE,             0,        9,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_CANDLE2*/ {	"Candle2",    SFX_NONE,    0,        TRUE,             2,        4,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_CANDLABR*///{	"Candlabr",   SFX_NONE,    0,       FALSE,             0,        1,         96, TRUE,      TRUE,     TRUE, OBM_UNBREAKABLE },
/*OFILE_NUDE2*/// {	"Nude2",      SFX_NONE,    0,        TRUE,             3,        6,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_SWITCH2*///{ "Switch2",    SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_SWITCH3*///{ "Switch3",    SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_SWITCH4*/ {	"Switch4",    SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_TNUDEM*/  {	"TNudeM",     SFX_NONE,    0,       FALSE,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_TNUDEW*/  {	"TNudeW",     SFX_NONE,    0,       FALSE,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_TSOUL*/   {	"TSoul",      SFX_NONE,    0,       FALSE,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_L2DOORS*/ {	"L2Doors",    IS_DOORCLOS, 2,       FALSE,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_WTORCH4*/ {	"WTorch4",    SFX_NONE,    0,        TRUE,             1,        9,         96, FALSE,      TRUE,      FALSE, OBM_UNBREAKABLE },
/*OFILE_WTORCH3*/ {	"WTorch3",    SFX_NONE,    0,        TRUE,             1,        9,         96, FALSE,      TRUE,      FALSE, OBM_UNBREAKABLE },
/*OFILE_SARC*/    {	"Sarc",       SFX_NONE,    0,       FALSE,             3,        5,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_FLAME1*///{ "Flame1",     SFX_NONE,    0,        TRUE,             1,       20,         96, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_FLAME3*///{ "Flame3",     SFX_NONE,    0,        TRUE,             1,       22,         96, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_FIREWAL1*///{ "Firewal1",   SFX_NONE,    0,        TRUE,             1,       13,        160, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_EXPLOD1*///{ "Explod1",    SFX_NONE,    0,        TRUE,             1,       11,        128, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_EXPLOD2*///{ "Explod2",    SFX_NONE,    0,        TRUE,             1,       11,        128, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_VAPOR1*///{ "Vapor1",     SFX_NONE,    0,         TRUE,             1,       13,        128, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_PRSRPLT1*///{ "Prsrplt1",   SFX_NONE,    0,       FALSE,             0,       10,         96, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_TRAPHOLE*/{	"Traphole",   SFX_NONE,    0,       FALSE,             0,        0,         64, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_DIRTFALL*///{ "Dirtfall",   SFX_NONE,    0,        TRUE,              0,       10,         96, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_WATER*/// { "Water",      SFX_NONE,    0,        TRUE,              1,       10,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_MINIWATR*///{ "MiniWatr",   SFX_NONE,    0,        TRUE,              1,       10,         64, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_WTORCH2*/ {	"WTorch2",    SFX_NONE,    0,        TRUE,             1,        9,         96, FALSE,      TRUE,      FALSE, OBM_UNBREAKABLE },
/*OFILE_WTORCH1*/ {	"WTorch1",    SFX_NONE,    0,        TRUE,             1,        9,         96, FALSE,      TRUE,      FALSE, OBM_UNBREAKABLE },
/*OFILE_BCASE*/   {	"BCase",      SFX_NONE,    0,       FALSE,             0,        0,         96, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_BSHELF*///{	"BShelf",     SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_WEAPSTND*/{	"WeapStnd",   SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_BKURNS*///{ "Bkurns",     SFX_NONE,    1,       FALSE,             1,       10,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE },
/*OFILE_WATERJUG*///{ "Waterjug",   SFX_NONE,   1,        FALSE,             1,        4,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE },
/*OFILE_BARREL*/  {	"Barrel",     IS_BARREL,   1,       FALSE,             1,        9,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE },
/*OFILE_BARRELEX*/{	"Barrelex",   IS_BARLFIRE, 1,       FALSE,             1,       10,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE },
/*OFILE_LSHRINEG*/{	"LShrineG",   IS_MAGIC,    2,       FALSE,             1,       11,        128, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_RSHRINEG*/{	"RShrineG",   IS_MAGIC,    2,       FALSE,             1,       11,        128, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_BLOODFNT*/{	"Bloodfnt",   SFX_NONE,    0,        TRUE,             2,       10,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_DECAP*/   {	"Decap",      SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_PEDISTL*/ {	"Pedistl",    SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_L3DOORS*/ {	"L3Doors",    IS_DOORCLOS, 2,       FALSE,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_PFOUNTN*/ {	"PFountn",    SFX_NONE,    0,        TRUE,             2,       10,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_ARMSTAND*/{	"Armstand",   SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_GOATSHRN*/{	"Goatshrn",   LS_GSHRINE,  1,        TRUE,             2,       10,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_CAULDREN*/{	"Cauldren",   LS_CALDRON,  1,       FALSE,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_MFOUNTN*/ {	"MFountn",    SFX_NONE,    0,        TRUE,             2,       10,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_TFOUNTN*/ {	"TFountn",    SFX_NONE,    0,        TRUE,             2,        4,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_ALTBOY*/  {	"Altboy",     SFX_NONE,    0,       FALSE,             0,        0,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_MCIRL*/   {	"Mcirl",      SFX_NONE,    0,       FALSE,             0,        0,         96, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_BKSLBRNT*/{	"Bkslbrnt",   SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_MUSHPTCH*/{	"Mushptch",   SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_LZSTAND*/ {	"LzStand",    SFX_NONE,    0,       FALSE,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE },
#ifdef HELLFIRE
/*OFILE_L5DOOR*/  {	"L5Door",     IS_CRCLOS,   2,       FALSE,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE },
/*OFILE_L5SARCO*/ {	"L5Sarco",    SFX_NONE,    0,       FALSE,             3,        5,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_URN*/     {	"Urn",        IS_POPPOP2,  1,       FALSE,             1,        9,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE },
/*OFILE_URNEXPLD*/{	"Urnexpld",   IS_POPPOP3,  1,       FALSE,             1,       10,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE },
/*OFILE_L5BOOKS*/ {	"L5Books",    SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_L5CANDLE*/{	"L5Light",    SFX_NONE,    0,        TRUE,             2,        4,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_L5LEVER*/ {	"L5Lever",    SFX_NONE,    0,       FALSE,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE },
/*OFILE_L6POD1*/  {	"L6Pod1",     IS_POPPOP5,  1,       FALSE,             1,        9,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE },
/*OFILE_L6POD2*/  {	"L6Pod2",     IS_POPPOP8,  1,       FALSE,             1,       10,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE },
#endif
	// clang-format on
};

DEVILUTION_END_NAMESPACE
