/**
 * @file objdat.cpp
 *
 * Implementation of all object data.
 */
#include "all.h"

DEVILUTION_BEGIN_NAMESPACE

/** Maps from dun_object_id to object_id. */
const BYTE ObjConvTbl[128] = {
	0,
	OBJ_LEVER, // Q_SKELKING
	OBJ_CRUXM, // Q_SKELKING
	OBJ_CRUXR, // Q_SKELKING
	OBJ_CRUXL, // Q_SKELKING
	0, //OBJ_ANGEL,
	0, //OBJ_BANNERL,
	0, //OBJ_BANNERM,
	0, //OBJ_BANNERR,
	0,
	0,
	0,
	0,
	0,
	OBJ_BOOK2L, // Q_SCHAMB, Q_BETRAYER
	0, //OBJ_BOOK2R,
	OBJ_TBCROSS, // Q_SCHAMB
	0,
	0, //OBJ_CANDLE1,
	OBJ_CANDLE2, // Q_SCHAMB
	0, //OBJ_CANDLEO,
	0, //OBJ_CAULDRON,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0, //OBJ_FLAMEHOLE,
	0,
	0,
	0,
	0,
	0,
	OBJ_MCIRCLE1, // Q_BETRAYER
	OBJ_MCIRCLE2, // Q_BETRAYER
	0, //OBJ_SKFIRE,
	0, //OBJ_SKPILE,
	0, //OBJ_SKSTICK1,
	0, //OBJ_SKSTICK2,
	0, //OBJ_SKSTICK3,
	0, //OBJ_SKSTICK4,
	0, //OBJ_SKSTICK5,
	0,
	0,
	0,
	0,
	0,
	0,
	OBJ_SWITCHSKL, // Q_SCHAMB
	0,
	0, //OBJ_TRAPL,
	0, //OBJ_TRAPR,
	OBJ_TORTURE1, // Q_BUTCHER
	OBJ_TORTURE2, // Q_BUTCHER
	OBJ_TORTURE3, // Q_BUTCHER
	OBJ_TORTURE4, // Q_BUTCHER
	OBJ_TORTURE5, // Q_BUTCHER
	0,
	0,
	0,
	0,
	0,
	0, //OBJ_NUDEW2R,
	0,
	0,
	0,
	0,
	OBJ_TNUDEM, //1, Q_BUTCHER
	OBJ_TNUDEM, //2, Q_BUTCHER
	OBJ_TNUDEM, //3, Q_BUTCHER
	OBJ_TNUDEM, //4, Q_BUTCHER
	OBJ_TNUDEW, //1, Q_BUTCHER
	OBJ_TNUDEW, //2, Q_BUTCHER
	OBJ_TNUDEW, //3, Q_BUTCHER
	0, //OBJ_CHEST1,
	OBJ_CHEST1, // Q_SKELKING
	0, //OBJ_CHEST1,
	0, //OBJ_CHEST2,
	OBJ_CHEST2, // Q_SKELKING
	0, //OBJ_CHEST2,
	0, //OBJ_CHEST3,
	OBJ_CHEST3, // Q_SCHAMB
	0, //OBJ_CHEST3,
	0,
	0,
	0,
	0,
	0,
	0, //OBJ_PEDISTAL,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	OBJ_ALTBOY, // Q_BETRAYER
	0,
	0,
	OBJ_ARMORSTAND, // Q_WARLORD
	OBJ_WEAPONRACKL, // Q_WARLORD
	OBJ_TORCHR2, // Q_BLOOD
	OBJ_TORCHL2, // Q_BLOOD
	0, //OBJ_MUSHPATCH,
	0, //OBJ_STAND,
	0, //OBJ_TORCHL,
	0, //OBJ_TORCHR,
	0, //OBJ_FLAMELVR,
	0, //OBJ_SARC,
	0, //OBJ_BARREL,
	0, //OBJ_BARRELEX,
	0, //OBJ_BOOKSHELF,
	0, //OBJ_BOOKCASEL,
	0, //OBJ_BOOKCASER,
	0, //OBJ_ARMORSTANDN,
	0, //OBJ_WEAPONRACKLN,
	0, //OBJ_BLOODFTN,
	0, //OBJ_PURIFYINGFTN,
	0, //OBJ_SHRINEL,
//	0, //OBJ_SHRINER,
//	0, //OBJ_GOATSHRINE,
//	0, //OBJ_MURKYFTN,
//	0, //OBJ_TEARFTN,
//	0, //OBJ_DECAP,
//	0, //OBJ_TCHEST1,
//	0, //OBJ_TCHEST2,
//	0, //OBJ_TCHEST3,
//	0, //OBJ_LAZSTAND,
//	0, //OBJ_BOOKSTAND,
//	0, //OBJ_BOOKSHELFR,
};

/** Contains the data related to each object ID. */
const ObjectData AllObjects[NUM_OBJECTS] = {
	// clang-format off
//_object_id          ofindex,        oLvlTypes,                                 oSetLvlType,     otheme,                  oquest,     oAnimFlag, oAnimBaseFrame, oAnimFrameLen, oAnimLen, oAnimWidth, oSolidFlag, oMissFlag, oLightFlag,     oBreak, oSelFlag, oTrapFlag
/*OBJ_L1LIGHT*/		{ OFILE_L1BRAZ,   DTM_CATHEDRAL,                             DTYPE_CATHEDRAL, THEME_NONE,              Q_INVALID,       TRUE,              0,             1,       26,         64, TRUE,       TRUE,      FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_L1LDOOR*/		{ OFILE_L1DOORS,  DTM_CATHEDRAL,                             DTYPE_CATHEDRAL, THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, TRUE      },
/*OBJ_L1RDOOR*/		{ OFILE_L1DOORS,  DTM_CATHEDRAL,                             DTYPE_CATHEDRAL, THEME_NONE,              Q_INVALID,      FALSE,              2,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, TRUE      },
/*OBJ_SKFIRE*/		{ OFILE_SKULFIRE, 0,                                         0,               THEME_SKELROOM,          Q_INVALID,       TRUE,              0,             2,       11,         96, TRUE,       TRUE,      FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_LEVER*/		{ OFILE_LEVER,    DTM_CATHEDRAL,                             0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, TRUE      },
/*OBJ_CHEST1*/		{ OFILE_CHEST1,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, TRUE      },
/*OBJ_CHEST2*/		{ OFILE_CHEST2,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, TRUE      },
/*OBJ_CHEST3*/		{ OFILE_CHEST3,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, TRUE      },
/*OBJ_CANDLE1*/	//	{ OFILE_L1BRAZ,   0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              0,             0,        0,          0, FALSE,      FALSE,     FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_CANDLE2*/		{ OFILE_CANDLE2,  0,                                         0,               THEME_SHRINE,            Q_INVALID,       TRUE,              0,             2,        4,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_CANDLEO*/	//	{ OFILE_L1BRAZ,   0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              0,             0,        0,          0, FALSE,      FALSE,     FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_BANNERL*/		{ OFILE_BANNER,   0,                                         0,               THEME_SKELROOM,          Q_INVALID,      FALSE,              2,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_BANNERM*/		{ OFILE_BANNER,   0,                                         0,               THEME_SKELROOM,          Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_BANNERR*/		{ OFILE_BANNER,   0,                                         0,               THEME_SKELROOM,          Q_INVALID,      FALSE,              3,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_SKPILE*/	//	{ OFILE_SKULPILE, 0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_SKSTICK1*///	{ OFILE_L1BRAZ,   0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              0,             0,        0,          0, FALSE,      FALSE,     FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_SKSTICK2*///	{ OFILE_L1BRAZ,   0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              0,             0,        0,          0, FALSE,      FALSE,     FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_SKSTICK3*///	{ OFILE_L1BRAZ,   0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              0,             0,        0,          0, FALSE,      FALSE,     FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_SKSTICK4*///	{ OFILE_L1BRAZ,   0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              0,             0,        0,          0, FALSE,      FALSE,     FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_SKSTICK5*///	{ OFILE_L1BRAZ,   0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              0,             0,        0,          0, FALSE,      FALSE,     FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_CRUXM*/		{ OFILE_CRUXSK1,  0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             1,       15,         96, TRUE,       FALSE,     TRUE,    OBM_BREAKABLE,        3, FALSE     },
/*OBJ_CRUXR*/		{ OFILE_CRUXSK2,  0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             1,       15,         96, TRUE,       FALSE,     TRUE,    OBM_BREAKABLE,        3, FALSE     },
/*OBJ_CRUXL*/		{ OFILE_CRUXSK3,  0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             1,       15,         96, TRUE,       FALSE,     TRUE,    OBM_BREAKABLE,        3, FALSE     },
/*OBJ_STAND*/		{ OFILE_ROCKSTAN, 0,                                         0,               THEME_NONE,              Q_ROCK,         FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_ANGEL*/	//	{ OFILE_ANGEL,    0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_NUDEW2R*/	//	{ OFILE_NUDE2,    0,                                         0,               THEME_NONE,              Q_INVALID,       TRUE,              0,             3,        6,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_SWITCHSKL*/	{ OFILE_SWITCH4,  DTM_HELL,                                  0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, TRUE      },
/*OBJ_TNUDEM*/		{ OFILE_TNUDEM,   DTM_HELL,                                  0,               THEME_TORTURE,           Q_BUTCHER,      FALSE,              0,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TNUDEW*/		{ OFILE_TNUDEW,   DTM_HELL,                                  0,               THEME_TORTURE,           Q_BUTCHER,      FALSE,              0,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TORTURE1*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,      FALSE,              1,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TORTURE2*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,      FALSE,              2,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TORTURE3*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,      FALSE,              3,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TORTURE4*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,      FALSE,              4,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TORTURE5*/	{ OFILE_TSOUL,    DTM_HELL,                                  0,               THEME_NONE,              Q_BUTCHER,      FALSE,              5,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_L2LDOOR*/		{ OFILE_L2DOORS,  DTM_CATACOMBS,                             DTYPE_CATACOMBS, THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, TRUE      },
/*OBJ_L2RDOOR*/		{ OFILE_L2DOORS,  DTM_CATACOMBS,                             DTYPE_CATACOMBS, THEME_NONE,              Q_INVALID,      FALSE,              2,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, TRUE      },
/*OBJ_TORCHL*/		{ OFILE_WTORCH4,  DTM_CATACOMBS,                             0,               THEME_NONE,              Q_INVALID,       TRUE,              0,             1,        9,         96, FALSE,      TRUE,      FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TORCHR*/		{ OFILE_WTORCH3,  DTM_CATACOMBS,                             0,               THEME_NONE,              Q_INVALID,       TRUE,              0,             1,        9,         96, FALSE,      TRUE,      FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TORCHL2*/		{ OFILE_WTORCH1,  DTM_CATACOMBS,                             0,               THEME_NONE,              Q_BLOOD,         TRUE,              0,             1,        9,         96, FALSE,      TRUE,      FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TORCHR2*/		{ OFILE_WTORCH2,  DTM_CATACOMBS,                             0,               THEME_NONE,              Q_BLOOD,         TRUE,              0,             1,        9,         96, FALSE,      TRUE,      FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_SARC*/		{ OFILE_SARC,     DTM_CATHEDRAL,                             0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             3,        5,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, TRUE      },
/*OBJ_FLAMEHOLE*///	{ OFILE_FLAME1,   0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             1,       20,         96, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_FLAMELVR*///	{ OFILE_LEVER,    0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        2,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, FALSE     },
/*OBJ_WATER*/	//	{ OFILE_MINIWATR, 0,                                         0,               THEME_NONE,              Q_INVALID,       TRUE,              0,             1,       10,         64, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TRAPL*/		{ OFILE_TRAPHOLE, DTM_CATHEDRAL | DTM_CATACOMBS,             0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         64, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TRAPR*/		{ OFILE_TRAPHOLE, DTM_CATHEDRAL | DTM_CATACOMBS,             0,               THEME_NONE,              Q_INVALID,      FALSE,              2,             0,        0,         64, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_BOOKSHELF*///	{ OFILE_BCASE,    0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_WEAPRACK*///	{ OFILE_WEAPSTND, 0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_BARREL*/		{ OFILE_BARREL,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             1,        9,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE,        3, FALSE     },
/*OBJ_BARRELEX*/	{ OFILE_BARRELEX, DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             1,       10,         96, TRUE,       TRUE,      TRUE,    OBM_BREAKABLE,        3, FALSE     },
/*OBJ_SHRINEL*/		{ OFILE_LSHRINEG, 0,                                         0,               THEME_SHRINE,            Q_INVALID,      FALSE,              1,             1,       11,        128, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_SHRINER*/		{ OFILE_RSHRINEG, 0,                                         0,               THEME_SHRINE,            Q_INVALID,      FALSE,              1,             1,       11,        128, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_BOOKCASEL*/	{ OFILE_BCASE,    0,                                         0,               THEME_LIBRARY,           Q_INVALID,      FALSE,              3,             0,        0,         96, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_BOOKCASER*/	{ OFILE_BCASE,    0,                                         0,               THEME_LIBRARY,           Q_INVALID,      FALSE,              4,             0,        0,         96, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_BOOKCANDLE*/	{ OFILE_CANDLE2,  0,                                         0,               THEME_LIBRARY,           Q_INVALID,       TRUE,              0,             2,        4,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_BLOODFTN*/	{ OFILE_BLOODFNT, 0,                                         0,               THEME_BLOODFOUNTAIN,     Q_INVALID,       TRUE,              0,             2,       10,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_DECAP*/		{ OFILE_DECAP,    DTM_HELL,                                  0,               THEME_DECAPITATED,       Q_INVALID,      FALSE,              0,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, FALSE     },
/*OBJ_TCHEST1*/		{ OFILE_CHEST1,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, FALSE     },
/*OBJ_TCHEST2*/		{ OFILE_CHEST2,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, FALSE     },
/*OBJ_TCHEST3*/		{ OFILE_CHEST3,   DTM_ANY,                                   0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, FALSE     },
/*OBJ_BOOK2L*/		{ OFILE_BOOK2,    0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_BOOK2R*/		{ OFILE_BOOK2,    0,                                         0,               THEME_NONE,              Q_SCHAMB,       FALSE,              4,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_BOOKSTAND*/	{ OFILE_BOOK2,    0,                                         0,               THEME_LIBRARY,           Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_SKELBOOK*/	{ OFILE_BOOK2,    0,                                         0,               THEME_SKELROOM,          Q_INVALID,      FALSE,              4,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_BOOKLVR*/	//	{ OFILE_BOOK1,    0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_BLINDBOOK*/	{ OFILE_BOOK1,    0,                                         0,               THEME_NONE,              Q_BLIND,        FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_BLOODBOOK*/	{ OFILE_BOOK1,    0,                                         0,               THEME_NONE,              Q_BLOOD,        FALSE,              4,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_STEELTOME*/	{ OFILE_BOOK1,    0,                                         0,               THEME_NONE,              Q_WARLORD,      FALSE,              4,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_PEDISTAL*/	{ OFILE_PEDISTL,  0,                                         0,               THEME_NONE,              Q_BLOOD,        FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_L3LDOOR*/		{ OFILE_L3DOORS,  DTM_CAVES,                                 DTYPE_CAVES,     THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, TRUE      },
/*OBJ_L3RDOOR*/		{ OFILE_L3DOORS,  DTM_CAVES,                                 DTYPE_CAVES,     THEME_NONE,              Q_INVALID,      FALSE,              2,             0,        0,         64, FALSE,      FALSE,     TRUE,  OBM_UNBREAKABLE,        3, TRUE      },
/*OBJ_PURIFYINGFTN*/{ OFILE_PFOUNTN,  0,                                         0,               THEME_PURIFYINGFOUNTAIN, Q_INVALID,       TRUE,              0,             2,       10,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_ARMORSTAND*/	{ OFILE_ARMSTAND, 0,                                         0,               THEME_ARMORSTAND,        Q_WARLORD,      FALSE,              1,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_ARMORSTANDN*/	{ OFILE_ARMSTAND, 0,                                         0,               THEME_ARMORSTAND,        Q_INVALID,      FALSE,              2,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_GOATSHRINE*/	{ OFILE_GOATSHRN, 0,                                         0,               THEME_GOATSHRINE,        Q_INVALID,       TRUE,              0,             2,       10,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_CAULDRON*/	{ OFILE_CAULDREN, DTM_HELL,                                  0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_MURKYFTN*/	{ OFILE_MFOUNTN,  0,                                         0,               THEME_MURKYFOUNTAIN,     Q_INVALID,       TRUE,              0,             2,       10,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_TEARFTN*/		{ OFILE_TFOUNTN,  0,                                         0,               THEME_TEARFOUNTAIN,      Q_INVALID,       TRUE,              0,             2,        4,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_ALTBOY*/		{ OFILE_ALTBOY,   0,                                         0,               THEME_NONE,              Q_BETRAYER,     FALSE,              1,             0,        0,        128, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_MCIRCLE1*/	{ OFILE_MCIRL,    0,                                         0,               THEME_NONE,              Q_BETRAYER,     FALSE,              1,             0,        0,         96, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_MCIRCLE2*/	{ OFILE_MCIRL,    0,                                         0,               THEME_NONE,              Q_BETRAYER,     FALSE,              3,             0,        0,         96, FALSE,      TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_STORYBOOK*/	{ OFILE_BKSLBRNT, DTM_CATHEDRAL | DTM_CATACOMBS | DTM_CAVES, 0,               THEME_NONE,              Q_INVALID,      FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     }, // BUGFIX should only be loaded on level 1-12 (crypt masks as 1-4) (fixed)
/*OBJ_STORYCANDLE*/	{ OFILE_CANDLE2,  DTM_CATHEDRAL | DTM_CATACOMBS | DTM_CAVES, 0,               THEME_NONE,              Q_BETRAYER,      TRUE,              0,             2,        4,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_TBCROSS*/		{ OFILE_BURNCROS, 0,                                         0,               THEME_BRNCROSS,          Q_INVALID,       TRUE,              0,             1,       10,        160, TRUE,       FALSE,     FALSE, OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_WEAPONRACKL*/	{ OFILE_WEAPSTND, 0,                                         0,               THEME_WEAPONRACK,        Q_WARLORD,      FALSE,              1,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_WEAPONRACKLN*/{ OFILE_WEAPSTND, 0,                                         0,               THEME_WEAPONRACK,        Q_INVALID,      FALSE,              2,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_WEAPONRACKR*/	{ OFILE_WEAPSTND, 0,                                         0,               THEME_WEAPONRACK,        Q_INVALID,      FALSE,              3,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_WEAPONRACKRN*/{ OFILE_WEAPSTND, 0,                                         0,               THEME_WEAPONRACK,        Q_INVALID,      FALSE,              4,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
/*OBJ_MUSHPATCH*/	{ OFILE_MUSHPTCH, 0,                                         0,               THEME_NONE,              Q_MUSHROOM,     FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_LAZSTAND*/	{ OFILE_LZSTAND,  0,                                         0,               THEME_NONE,              Q_BETRAYER,     FALSE,              1,             0,        0,        128, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        3, FALSE     },
/*OBJ_SLAINHERO*/	{ OFILE_DECAP,    DTM_CAVES,                                 0,               THEME_NONE,              Q_INVALID,      FALSE,              2,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, FALSE     },
/*OBJ_SIGNCHEST*/	{ OFILE_CHEST3,   0,                                         0,               THEME_NONE,              Q_LTBANNER,     FALSE,              1,             0,        0,         96, TRUE,       TRUE,      TRUE,  OBM_UNBREAKABLE,        1, FALSE     },
/*OBJ_BOOKSHELFR*///{ OFILE_BCASE,    0,                                         0,               THEME_NONE,              Q_INVALID,      FALSE,              2,             0,        0,         96, TRUE,       FALSE,     TRUE,  OBM_UNBREAKABLE,        0, FALSE     },
	// clang-format on
};

/** Maps from object_graphic_id to object CEL name. */
const char *const ObjMasterLoadList[NUM_OFILE_TYPES] = {
	// clang-format off
//object_graphic_id
/*OFILE_L1BRAZ*/  {	"L1Braz" },
/*OFILE_L1DOORS*/ {	"L1Doors" },
/*OFILE_LEVER*/   {	"Lever" },
/*OFILE_CHEST1*/  {	"Chest1" },
/*OFILE_CHEST2*/  {	"Chest2" },
/*OFILE_BANNER*/  {	"Banner" },
/*OFILE_SKULPILE*/{	"SkulPile" },
/*OFILE_SKULFIRE*/{	"SkulFire" },
/*OFILE_SKULSTIK*/{	"SkulStik" },
/*OFILE_CRUXSK1*/ {	"CruxSk1" },
/*OFILE_CRUXSK2*/ {	"CruxSk2" },
/*OFILE_CRUXSK3*/ {	"CruxSk3" },
/*OFILE_BOOK1*/   {	"Book1" },
/*OFILE_BOOK2*/   {	"Book2" },
/*OFILE_ROCKSTAN*/{	"Rockstan" },
/*OFILE_ANGEL*/   {	"Angel" },
/*OFILE_CHEST3*/  {	"Chest3" },
/*OFILE_BURNCROS*/{	"Burncros" },
/*OFILE_CANDLE2*/ {	"Candle2" },
/*OFILE_NUDE2*/   {	"Nude2" },
/*OFILE_SWITCH4*/ {	"Switch4" },
/*OFILE_TNUDEM*/  {	"TNudeM" },
/*OFILE_TNUDEW*/  {	"TNudeW" },
/*OFILE_TSOUL*/   {	"TSoul" },
/*OFILE_L2DOORS*/ {	"L2Doors" },
/*OFILE_WTORCH4*/ {	"WTorch4" },
/*OFILE_WTORCH3*/ {	"WTorch3" },
/*OFILE_SARC*/    {	"Sarc" },
/*OFILE_FLAME1*/  {	"Flame1" },
/*OFILE_PRSRPLT1*/{	"Prsrplt1" },
/*OFILE_TRAPHOLE*/{	"Traphole" },
/*OFILE_MINIWATR*/{	"MiniWatr" },
/*OFILE_WTORCH2*/ {	"WTorch2" },
/*OFILE_WTORCH1*/ {	"WTorch1" },
/*OFILE_BCASE*/   {	"BCase" },
/*OFILE_BSHELF*/  {	"BShelf" },
/*OFILE_WEAPSTND*/{	"WeapStnd" },
/*OFILE_BARREL*/  {	"Barrel" },
/*OFILE_BARRELEX*/{	"Barrelex" },
/*OFILE_LSHRINEG*/{	"LShrineG" },
/*OFILE_RSHRINEG*/{	"RShrineG" },
/*OFILE_BLOODFNT*/{	"Bloodfnt" },
/*OFILE_DECAP*/   {	"Decap" },
/*OFILE_PEDISTL*/ {	"Pedistl" },
/*OFILE_L3DOORS*/ {	"L3Doors" },
/*OFILE_PFOUNTN*/ {	"PFountn" },
/*OFILE_ARMSTAND*/{	"Armstand" },
/*OFILE_GOATSHRN*/{	"Goatshrn" },
/*OFILE_CAULDREN*/{	"Cauldren" },
/*OFILE_MFOUNTN*/ {	"MFountn" },
/*OFILE_TFOUNTN*/ {	"TFountn" },
/*OFILE_ALTBOY*/  {	"Altboy" },
/*OFILE_MCIRL*/   {	"Mcirl" },
/*OFILE_BKSLBRNT*/{	"Bkslbrnt" },
/*OFILE_MUSHPTCH*/{	"Mushptch" },
/*OFILE_LZSTAND*/ {	"LzStand" },
	// clang-format on
};

#ifdef HELLFIRE
/** Maps from object_graphic_id to object CEL name (Hellfire Crypt overwrite). */
const char *const ObjCryptLoadList[NUM_OFILE_TYPES] = {
	"L1Braz",
	"L5Door",
	"L5Lever",
	"Chest1",
	"Chest2",
	"Banner",
	"SkulPile",
	"SkulFire",
	"SkulStik",
	"CruxSk1",
	"CruxSk2",
	"CruxSk3",
	"Book1",
	"Book2",
	"Rockstan",
	"Angel",
	"Chest3",
	"Burncros",
	"L5Light",
	"Nude2",
	"Switch4",
	"TNudeM",
	"TNudeW",
	"TSoul",
	"L2Doors",
	"WTorch4",
	"WTorch3",
	"L5Sarco",
	"Flame1",
	"Prsrplt1",
	"Traphole",
	"MiniWatr",
	"WTorch2",
	"WTorch1",
	"BCase",
	"BShelf",
	"WeapStnd",
	"Urn",
	"Urnexpld",
	"LShrineG",
	"RShrineG",
	"Bloodfnt",
	"Decap",
	"Pedistl",
	"L3Doors",
	"PFountn",
	"Armstand",
	"Goatshrn",
	"Cauldren",
	"MFountn",
	"TFountn",
	"Altboy",
	"Mcirl",
	"L5Books",
	"Mushptch",
	"LzStand",
};
/** Maps from object_graphic_id to object CEL name (Hellfire Nest overwrite). */
const char *const ObjNestLoadList[NUM_OFILE_TYPES] = {
	"L1Braz",
	"L1Doors",
	"Lever",
	"Chest1",
	"Chest2",
	"Banner",
	"SkulPile",
	"SkulFire",
	"SkulStik",
	"CruxSk1",
	"CruxSk2",
	"CruxSk3",
	"Book1",
	"Book2",
	"Rockstan",
	"Angel",
	"Chest3",
	"Burncros",
	"Candle2",
	"Nude2",
	"Switch4",
	"TNudeM",
	"TNudeW",
	"TSoul",
	"L2Doors",
	"WTorch4",
	"WTorch3",
	"Sarc",
	"Flame1",
	"Prsrplt1",
	"Traphole",
	"MiniWatr",
	"WTorch2",
	"WTorch1",
	"BCase",
	"BShelf",
	"WeapStnd",
	"L6Pod1",
	"L6Pod2",
	"LShrineG",
	"RShrineG",
	"Bloodfnt",
	"Decap",
	"Pedistl",
	"L3Doors",
	"PFountn",
	"Armstand",
	"Goatshrn",
	"Cauldren",
	"MFountn",
	"TFountn",
	"Altboy",
	"Mcirl",
	"Bkslbrnt",
	"Mushptch",
	"LzStand",
};
#endif

DEVILUTION_END_NAMESPACE
