/**
 * @file trndat.cpp
 *
 * Interface of data related to gfx-translations (trn).
 */
#include "all.h"
#include "trndat.h"

DEVILUTION_BEGIN_NAMESPACE

const TRNFileData trnfiledata[NUM_TRNS + 1] = {
	// clang-format off
//_trn_id                  trnName
                           { NULL },
/* TRN_MON_ZOMBIE_BR */    { "Zombie\\Bluered" },
/* TRN_MON_ZOMBIE_GREY */  { "Zombie\\Grey" },
/* TRN_MON_ZOMBIE_YEL */   { "Zombie\\Yellow" },
/* TRN_MON_FALLSP_FALT */  { "FalSpear\\FallenT" },
/* TRN_MON_FALLSP_DARK */  { "FalSpear\\Dark" },
/* TRN_MON_FALLSP_BLUE */  { "FalSpear\\Blue" },
/* TRN_MON_SKELSD_WHITE */ { "SkelSd\\White" },
/* TRN_MON_SKELSD_SKELT */ { "SkelSd\\Skelt" },
/* TRN_MON_SKELSD_BLACK */ { "SkelSd\\Black" },
/* TRN_MON_SCAV_BR */      { "Scav\\ScavBr" },
/* TRN_MON_SCAV_BE */      { "Scav\\ScavBe" },
/* TRN_MON_SCAV_WHITE */   { "Scav\\ScavW" },
/* TRN_MON_SNEAK_V1 */     { "Sneak\\Sneakv1" },
/* TRN_MON_SNEAK_V2 */     { "Sneak\\Sneakv2" },
/* TRN_MON_SNEAK_V3 */     { "Sneak\\Sneakv3" },
/* TRN_MON_GOATMC_BEIGE */ { "GoatMace\\Beige" },
/* TRN_MON_GOATMC_RED */   { "GoatMace\\Red" },
/* TRN_MON_GOATMC_GRAY */  { "GoatMace\\Gray" },
/* TRN_MON_BAT_RED */      { "Bat\\red" },
/* TRN_MON_BAT_GREY */     { "Bat\\grey" },
/* TRN_MON_BAT_ORANGE */   { "Bat\\orange" },
/* TRN_MON_ACID_BLK */     { "Acid\\AcidBlk" },
/* TRN_MON_ACID_BLUE */    { "Acid\\AcidB" },
/* TRN_MON_ACID_RED */     { "Acid\\AcidR" },
/* TRN_MON_FAT_BLUE */     { "Fat\\Blue" },
/* TRN_MON_FAT_BG */       { "Fat\\FatB" },
/* TRN_MON_FAT_RED */      { "Fat\\FatF" },
/* TRN_MON_MAGMA_YEL */    { "Magma\\Yellow" },
/* TRN_MON_MAGMA_BLUE */   { "Magma\\Blue" },
/* TRN_MON_MAGMA_WIERD */  { "Magma\\Wierd" },
/* TRN_MON_RHINO_ORANGE */ { "Rhino\\Orange" },
/* TRN_MON_RHINO_BLUE */   { "Rhino\\Blue" },
/* TRN_MON_RHINO_BR */     { "Rhino\\RhinoB" },
/* TRN_MON_THIN_V1 */      { "Thin\\Thinv1" },
/* TRN_MON_THIN_V2 */      { "Thin\\Thinv2" },
/* TRN_MON_THIN_V3 */      { "Thin\\Thinv3" },
/* TRN_MON_GARG_E */       { "Gargoyle\\GarE" },
/* TRN_MON_GARG_BR */      { "Gargoyle\\GargBr" },
/* TRN_MON_GARG_BLUE */    { "Gargoyle\\GargB" },
/* TRN_MON_MEGA_GUARD */   { "Mega\\Guard" },
/* TRN_MON_MEGA_VTEXL */   { "Mega\\Vtexl" },
/* TRN_MON_MEGA_BALR */    { "Mega\\Balr" },
/* TRN_MON_SNAKE_R */      { "Snake\\SnakR" },
/* TRN_MON_SNAKE_G */      { "Snake\\Snakg" },
/* TRN_MON_SNAKE_B */      { "Snake\\Snakb" },
/* TRN_MON_BLACK_RT */     { "Black\\BlkKntRT" },
/* TRN_MON_BLACK_BT */     { "Black\\BlkKntBT" },
/* TRN_MON_BLACK_BE */     { "Black\\BlkKntBe" },
/* TRN_MON_SUCC_B */       { "Succ\\Succb" },
/* TRN_MON_SUCC_RW */      { "Succ\\Succrw" },
/* TRN_MON_SUCC_BW */      { "Succ\\Succbw" },
/* TRN_MON_MAGE_G */       { "Mage\\Cnselg" },
/* TRN_MON_MAGE_GD */      { "Mage\\Cnselgd" },
/* TRN_MON_MAGE_BK */      { "Mage\\Cnselbk" },

/* TRN_UMON_BSDB */        { "BSDB" },
/* TRN_UMON_GENERAL */     { "GENERAL" },
/* TRN_UMON_BNG */         { "BNG" },
/* TRN_UMON_REDV */        { "REDV" },
/* TRN_UMON_BLKJD */       { "BLKJD" },
/* TRN_UMON_BHKA */        { "BHKA" },
/* TRN_UMON_BSTS */        { "BSTS" },
/* TRN_UMON_PTU */         { "PTU" },
/* TRN_UMON_BR */          { "BR" },
/* TRN_UMON_ETH */         { "ETH" },
/* TRN_UMON_SHBT */        { "SHBT" },
/* TRN_UMON_DE */          { "DE" },
/* TRN_UMON_GTQ */         { "GTQ" },
/* TRN_UMON_BHBS */        { "BHBS" },
/* TRN_UMON_RCRN */        { "RCRN" },
/* TRN_UMON_SKFR */        { "SKFR" },
/* TRN_UMON_TSPO */        { "TSPO" },
/* TRN_UMON_PMR */         { "PMR" },
/* TRN_UMON_MTD */         { "MTD" },
/* TRN_UMON_BASHTB */      { "BASHTB" },
/* TRN_UMON_DB */          { "DB" },
/* TRN_UMON_SHDR */        { "SHDR" },
/* TRN_UMON_BFTP */        { "BFTP" },
/* TRN_UMON_BFDS */        { "BFDS" },
/* TRN_UMON_BGBL */        { "BGBL" },
/* TRN_UMON_DSFM */        { "DSFM" },
/* TRN_UMON_BLF */         { "BLF" },
/* TRN_UMON_BHSM */        { "BHSM" },
/* TRN_UMON_BSM */         { "BSM" },
/* TRN_UMON_WFTD */        { "WFTD" },

/* TRN_PLR_STONE */        { "Stone" },
/* TRN_PLR_BLUE */         { "Blue" },
/* TRN_PLR_GRAY */         { "Gray" },
/* TRN_PLR_NONE */         { "None" },
/* TRN_PLR_ORANGE */       { "Orange" },
/* TRN_PLR_CORAL */        { "Coral" },
/* TRN_PLR_INFRA */        { "Infra" },
/* TRN_PLR_RED */          { "Red" },

	// clang-format on
};

DEVILUTION_END_NAMESPACE
