name: Test

# When creating a new workflow in GitHub’s action builder the default trigger is the push event. We want to extend this to push and pull request events.
on: [push, pull_request]

env:
  buildDir: '${{ github.workspace }}/build'

jobs:
  build0:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  # Windows-builds
  build1:
    needs: build0
	if: ${{ needs.check_date.outputs.should_run != 'false' }}
    name: Nightly-Win
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        name: [hellfire-x86]
        include:
          # x86 builds
          - name: hellfire-x86
            packages: 'sdl2:x86-windows sdl2-mixer:x86-windows sdl2-ttf:x86-windows libsodium:x86-windows'
            cmakeargs: '-A Win32 -D_WIN32_WINNT=0x0501 -D HELLFIRE=ON -D ZEROTIER=ON'
            artifact: 'hellfire-test-x86.zip'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
    - name: Create Build Environment
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
        vcpkgGitCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
    # Now that vcpkg is installed, it is being used to run with the desired arguments.
    - run: |
        $VCPKG_ROOT/vcpkg install ${{ matrix.packages }}
      shell: bash

    - name: Configure CMake
      shell: bash
      working-directory: ${{ env.buildDir }}
      run: cmake .. ${{ matrix.cmakeargs }} -D BINARY_RELEASE="ON" -D CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: Build
      working-directory: ${{ env.buildDir }}
      shell: bash
    # Execute the build (-j 2 : with two cores).
      run: cmake --build . -j 2 --target package --config Release

    # Upload the created artifact
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: ${{ env.buildDir }}/devilutionx.zip
        name: ${{ matrix.artifact }}
  # Releases
  release:
    needs: [build0, build1]
	if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: windows-latest
    steps:
    # x86 builds
    - name: Download a hellfire artifact
      uses: actions/download-artifact@v2
      with:
        name: hellfire-test-x86.zip
    - run: mv ${{github.workspace}}/devilutionx.zip ${{github.workspace}}/hellfire-test-x86.zip

    - name: Show content of workspace
      run: find $RUNNER_WORKSPACE
      shell: bash

    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: devilx-test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: devilx-test
        body: test
        draft: false
        prerelease: true
        files: |
          ${{github.workspace}}/hellfire-test-x86.zip
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
