name: Xbox-nxdk

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  xbox:
    # `ubuntu-latest` is currently 20.04 but we require a newer clang.
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: diablo
            cmakeargs: '-DUSE_PATCH=OFF'
            artifact: 'diablo-push-xbox-nxdk'
          - name: hellfire+patch
            cmakeargs: '-DHELLFIRE=ON'
            artifact: 'hellfire-push-xbox-nxdkp'
    env:
      NXDK_DIR: /opt/nxdk
    steps:
    - name: Create Build Environment
      run: sudo apt-get update && sudo apt-get install -y clang llvm lld bison flex cmake git gettext smpq

    - name: Clone NXDK Repo
      shell: bash
      #run: git clone --recursive --depth 1 --branch devilutionx https://github.com/glebm/nxdk.git "$NXDK_DIR"
      run: git clone --recursive --depth 0 https://github.com/XboxDev/nxdk.git "$NXDK_DIR"

    - name: Build NXDK
      shell: bash
      run: PATH="${NXDK_DIR}/bin:$PATH" make -j $(nproc) -C "$NXDK_DIR" NXDK_ONLY=1 all cxbe extract-xiso

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -S. -Bbuild-xbox ${{ matrix.cmakeargs }} -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/opt/nxdk/share/toolchain-nxdk.cmake

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build build-xbox -j $(nproc) --target nxdk_xbe

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: build-xbox/pkg/default.xbe
