name: CMake

# When creating a new workflow in GitHub’s action builder the default trigger is the push event. We want to extend this to push and pull request events.
on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Head-VITA
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: diablo
            cmakeargs: '-D DEVILUTIONX_SYSTEM_SDL2=OFF'
            artifact: 'diablo-head-vita.vpk'
          - name: hellfire
            cmakeargs: '-D DEVILUTIONX_SYSTEM_SDL2=OFF -DHELLFIRE=ON'
            artifact: 'hellfire-head-vita.vpk'
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-tags: true
      #  fetch-depth: 0

    - name: Create Build Environment
      #run: apk add cmake ninja
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build

    - name: Configure CMake
      run: |
        cmake -S. -Bbuild -GNinja \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{ matrix.cmakeargs }} \
          -DCMAKE_TOOLCHAIN_FILE=${VITASDK}/share/vita.toolchain.cmake

    - name: Build
      run: cmake --build build -j $(sysctl -n hw.physicalcpu) --config ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact }}
        path: build/devilutionx.vpk
